### ISSUE TITLE
Unable to build as dependency meta-compulab-uefi is a private repo

### ISSUE THREAD

**Issue by akash-roboticist** [compulab-yokneam/compulab-fslc-bsp#1]
While trying to build mender `kirkstone` image for `iot-gate-imx8` , instructions call for 
>Initialize FSL comunity & CompuLab repo manifests

`meta-compulab-uefi` repo defined in the script though is private
https://github.com/compulab-yokneam/compulab-fslc-bsp/blob/8b23b72972758a4760c22ce9eb2d06851ac3ecb7/scripts/compulab-bsp-setup-iot.xml#L14

Can this be updated to be public / instructions updated to perhaps use a different repo that is public? @vraevsky

**Comment by vraevsky** [comment]
> While trying to build mender `kirkstone` image for `iot-gate-imx8` , instructions call for
> 
> > Initialize FSL comunity & CompuLab repo manifests
> 
> `meta-compulab-uefi` repo defined in the script though is private
> 
> https://github.com/compulab-yokneam/compulab-fslc-bsp/blob/8b23b72972758a4760c22ce9eb2d06851ac3ecb7/scripts/compulab-bsp-setup-iot.xml#L14
> 
> Can this be updated to be public / instructions updated to perhaps use a different repo that is public? @vraevsky

Switched to public, try it now.

**Comment by akash-roboticist** [comment]
Thanks , it is accessible now.
